// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwqJtm7qv5PvBH1zbMCgEg-cmFoFw_-fQ',
    appId: '1:257292082474:web:1df412405b7a0c6e715253',
    messagingSenderId: '257292082474',
    projectId: 'capstone-flood-monitoring',
    authDomain: 'capstone-flood-monitoring.firebaseapp.com',
    storageBucket: 'capstone-flood-monitoring.firebasestorage.app',
    measurementId: 'G-8FGGJCGYC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmsvFSEBxkV1Zn2vjW1oGI1KcM0y_UdT0',
    appId: '1:257292082474:android:7a4bc79c82b9f517715253',
    messagingSenderId: '257292082474',
    projectId: 'capstone-flood-monitoring',
    storageBucket: 'capstone-flood-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEpdo96aDBs7yNM_qS07tw9P__dSR1Fww',
    appId: '1:257292082474:ios:fac8c6e85dbcabe9715253',
    messagingSenderId: '257292082474',
    projectId: 'capstone-flood-monitoring',
    storageBucket: 'capstone-flood-monitoring.firebasestorage.app',
    iosBundleId: 'com.capstone.floodMonitoringAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpdo96aDBs7yNM_qS07tw9P__dSR1Fww',
    appId: '1:257292082474:ios:fac8c6e85dbcabe9715253',
    messagingSenderId: '257292082474',
    projectId: 'capstone-flood-monitoring',
    storageBucket: 'capstone-flood-monitoring.firebasestorage.app',
    iosBundleId: 'com.capstone.floodMonitoringAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwqJtm7qv5PvBH1zbMCgEg-cmFoFw_-fQ',
    appId: '1:257292082474:web:af6e8e717ab9996f715253',
    messagingSenderId: '257292082474',
    projectId: 'capstone-flood-monitoring',
    authDomain: 'capstone-flood-monitoring.firebaseapp.com',
    storageBucket: 'capstone-flood-monitoring.firebasestorage.app',
    measurementId: 'G-6W21QSQCN5',
  );
}
